# Generated by Django 5.2.1 on 2025-05-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日付')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
            ],
        ),
    ]
