# Generated by Django 5.2.1 on 2025-05-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='タグ')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='tags',
            field=models.ManyToManyField(related_name='タグ', to='mylog.tag'),
        ),
    ]
