# Generated by Django 5.2.1 on 2025-05-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='画像'),
        ),
    ]
