# Generated by Django 5.2.1 on 2025-05-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
