# Generated by Django 5.2.1 on 2025-05-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylog', '0002_log_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logs/', verbose_name='画像'),
        ),
    ]
